# tables=r""
# CREATE TABLE first_table(
#     FIRST_NAME VARCHAR(255) NOT NULL,
#     LAST_NAME VARCHAR(255) NOT NULL,
#     DOB DATE CHECK(DOB >'1900-01-01')
#     COMPANY_ID INTEGER NOT NULL,
#     LAST_ACTIVE DATE NOT NULL,
#     SCORE INTEGER NOT NULL,
#     MEMBER_SINCE INTEGER NOT NULL,
#     STATE CHAR(2) NOT NULL
# )
# CREATE TABLE second_table(
#     NAME VARCHAR(255) NOT NULL,
#     DATE_OF_BIRTH DATE CHECK(DOB >'1900-01-01'),
#     COMPANY_ID INTEGER NOT NULL,
#     LAST_ACTIVE DATE NOT NULL,
#     SCORE INTEGER NOT NULL,
#     JOINED_LEAGUE INTEGER NOT NULL,
#     US_STATE VARCHAR(255) NOT NULL
# )""